config/routes.rb
Rails.application.routes.draw do
  
  resources :repeat

end

app/models/repeat.rb
class Repeat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/repeat_controller.rb
class RepeatController < ApplicationController
  
  def index
  	@repeats = Repeat.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repeat_helper.rb
module RepeatHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RepeatTextboxSlideExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/repeat/_form.html.erb
<%= form_for(@repeat) do |f| %>
  <% if @repeat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repeat.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @repeat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repeat/index.html.erb
<h1>Listing Repeat Textbox</h1>

<% 
  def create_row( number )
  	row = %q(
	)
  end
%>


<% @numbers = ['1','2','3','4','5'] %>

<table>
  <thead>
    <tr>
      <th>Textbox Number</th>
      <th colspan='2'>Actions</th>
    </tr>
  </thead>

  <tbody>

  	<% @numbers.each do |number| %>
  	  <tr>
	  	<td><%= number %></td>
	  	<td>
	  	  <% id = number %>
	  	  <% show_id = 'show-form-' + id %>
	  	  <% input_id = 'input-form-' + id %>
	  	  <% submit_id = 'submit-form-' +  id %>
	  	  <% cancel_id = 'cancel-form-' +  id %>
	  	  <div>
	  	  	<button id=<%= show_id %>>Click</button>
	  	  </div>

	      <div id=<%= input_id %> class='input'>

		  <p>
		  	<textarea></textarea>
		  </p>	
		  	
		  <button id=<%= submit_id %> >Submit</button>
		  <button id=<%= cancel_id %> >Cancel</button>

		  </div>	
	  	</td>
	  </tr>
  	<% end %>
  	
  </tbody>

</table>

<%= link_to 'New Textbox', new_repeat_path %>

<script type="text/javascript">

	$(document).ready(function() {
		$(".input").hide();
	});

	var junction = '-form-'

  	$('button').click(function(event) {
  		var selector = event.target.id.split('-')
  		var id = selector [2]
  		var method = selector [0]

  		switch(method) {
  			case 'show' : show_form("#input" + junction + id)
  							break
  			case 'cancel' : hide_form("#input" + junction + id)
  							break
  			case 'submit' : alert('submit' + id)
  							break
  		}
  		
  	});

  	function show_form(id) {
  		$(id).slideDown();
  	}

  	function hide_form(id) {
  		$(id).slideUp();
  	}

  </script>

app/views/repeat/new.html.erb
<h1>New Textbox</h1>

<%= render 'form' %>

<%= link_to 'Back', repeat_index_path %>